### ISSUE TITLE
리포지토리 설명과 사이트 URL 등록 요청

### ISSUE THREAD

**Issue by jinhoyim** [AutoParams/autoparams.github.io#10]
GitHub 리포지토리 우측 상단에 리포지토리 설명과 사이트 URL 등록을 요청합니다.

**Comment by gyuwon** [comment]
설명을 어떻게 변경하면 좋을까요?

**Comment by jinhoyim** [comment]
웹 링크가 추가되고 보니 설명은 없어도 괜찮을 것 같습니다.
