### ISSUE TITLE
GitHub Pages 빌드 배포 설정 변경

### ISSUE THREAD

**Issue by jinhoyim** [AutoParams/autoparams.github.io#3]
GitHub Actions 를 사용하여 빌드와 배포가 동작할 수 있도록 `Settings - Pages - Build and deployment` 섹션의 `Source`를 `Deploy from a branch` 에서 `GitHub Actions`로 변경을 요청합니다.

`Deploy from a branch` 설정은 기본 빌드 프로세스가 추가로 동작하고 배포 중 웹페이지가 중단됩니다.

**Comment by gyuwon** [comment]
변경했습니다. 확인 부탁드려요. :)

**Comment by jinhoyim** [comment]
잘 동작합니다. 감사합니다.
